/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserAccountsRouteImport } from './routes/user/accounts'
import { Route as RPuuidRouteImport } from './routes/r.$puuid'
import { Route as LolLiveRouteImport } from './routes/lol/live'
import { Route as LolFeedRouteRouteImport } from './routes/lol/feed/route'
import { Route as LolSummonerIndexRouteImport } from './routes/lol/summoner/index'
import { Route as LolFeedIndexRouteImport } from './routes/lol/feed/index'
import { Route as LolFeedForYouRouteImport } from './routes/lol/feed/for-you'
import { Route as LolFeedFollowingRouteImport } from './routes/lol/feed/following'
import { Route as LolFeaturedGamesRegionRouteImport } from './routes/lol/featured-games/$region'
import { Route as LolSummonerRiotIDRouteRouteImport } from './routes/lol/summoner/$riotID/route'
import { Route as LolSummonerRiotIDIndexRouteImport } from './routes/lol/summoner/$riotID/index'
import { Route as LolSummonerRiotIDMatchesRouteImport } from './routes/lol/summoner/$riotID/matches'
import { Route as LolSummonerRiotIDMasteryRouteImport } from './routes/lol/summoner/$riotID/mastery'
import { Route as LolSummonerRiotIDLiveRouteImport } from './routes/lol/summoner/$riotID/live'
import { Route as LolSummonerRiotIDChartsRouteImport } from './routes/lol/summoner/$riotID/charts'
import { ServerRoute as SitemapXmlServerRouteImport } from './routes/sitemap.xml'
import { ServerRoute as SitemapStaticXmlServerRouteImport } from './routes/sitemap-static.xml'
import { ServerRoute as RobotsTxtServerRouteImport } from './routes/robots.txt'
import { ServerRoute as SitemapSummonersPageXmlServerRouteImport } from './routes/sitemap-summoners/$page.xml'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAccountsRoute = UserAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => UserRouteRoute,
} as any)
const RPuuidRoute = RPuuidRouteImport.update({
  id: '/r/$puuid',
  path: '/r/$puuid',
  getParentRoute: () => rootRouteImport,
} as any)
const LolLiveRoute = LolLiveRouteImport.update({
  id: '/lol/live',
  path: '/lol/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LolFeedRouteRoute = LolFeedRouteRouteImport.update({
  id: '/lol/feed',
  path: '/lol/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LolSummonerIndexRoute = LolSummonerIndexRouteImport.update({
  id: '/lol/summoner/',
  path: '/lol/summoner/',
  getParentRoute: () => rootRouteImport,
} as any)
const LolFeedIndexRoute = LolFeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LolFeedRouteRoute,
} as any)
const LolFeedForYouRoute = LolFeedForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => LolFeedRouteRoute,
} as any)
const LolFeedFollowingRoute = LolFeedFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => LolFeedRouteRoute,
} as any)
const LolFeaturedGamesRegionRoute = LolFeaturedGamesRegionRouteImport.update({
  id: '/lol/featured-games/$region',
  path: '/lol/featured-games/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const LolSummonerRiotIDRouteRoute = LolSummonerRiotIDRouteRouteImport.update({
  id: '/lol/summoner/$riotID',
  path: '/lol/summoner/$riotID',
  getParentRoute: () => rootRouteImport,
} as any)
const LolSummonerRiotIDIndexRoute = LolSummonerRiotIDIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LolSummonerRiotIDRouteRoute,
} as any)
const LolSummonerRiotIDMatchesRoute =
  LolSummonerRiotIDMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => LolSummonerRiotIDRouteRoute,
  } as any)
const LolSummonerRiotIDMasteryRoute =
  LolSummonerRiotIDMasteryRouteImport.update({
    id: '/mastery',
    path: '/mastery',
    getParentRoute: () => LolSummonerRiotIDRouteRoute,
  } as any)
const LolSummonerRiotIDLiveRoute = LolSummonerRiotIDLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LolSummonerRiotIDRouteRoute,
} as any)
const LolSummonerRiotIDChartsRoute = LolSummonerRiotIDChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => LolSummonerRiotIDRouteRoute,
} as any)
const SitemapXmlServerRoute = SitemapXmlServerRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const SitemapStaticXmlServerRoute = SitemapStaticXmlServerRouteImport.update({
  id: '/sitemap-static/xml',
  path: '/sitemap-static/xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const RobotsTxtServerRoute = RobotsTxtServerRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootServerRouteImport,
} as any)
const SitemapSummonersPageXmlServerRoute =
  SitemapSummonersPageXmlServerRouteImport.update({
    id: '/sitemap-summoners/$page/xml',
    path: '/sitemap-summoners/$page/xml',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/lol/feed': typeof LolFeedRouteRouteWithChildren
  '/lol/live': typeof LolLiveRoute
  '/r/$puuid': typeof RPuuidRoute
  '/user/accounts': typeof UserAccountsRoute
  '/user/settings': typeof UserSettingsRoute
  '/lol/summoner/$riotID': typeof LolSummonerRiotIDRouteRouteWithChildren
  '/lol/featured-games/$region': typeof LolFeaturedGamesRegionRoute
  '/lol/feed/following': typeof LolFeedFollowingRoute
  '/lol/feed/for-you': typeof LolFeedForYouRoute
  '/lol/feed/': typeof LolFeedIndexRoute
  '/lol/summoner': typeof LolSummonerIndexRoute
  '/lol/summoner/$riotID/charts': typeof LolSummonerRiotIDChartsRoute
  '/lol/summoner/$riotID/live': typeof LolSummonerRiotIDLiveRoute
  '/lol/summoner/$riotID/mastery': typeof LolSummonerRiotIDMasteryRoute
  '/lol/summoner/$riotID/matches': typeof LolSummonerRiotIDMatchesRoute
  '/lol/summoner/$riotID/': typeof LolSummonerRiotIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/lol/live': typeof LolLiveRoute
  '/r/$puuid': typeof RPuuidRoute
  '/user/accounts': typeof UserAccountsRoute
  '/user/settings': typeof UserSettingsRoute
  '/lol/featured-games/$region': typeof LolFeaturedGamesRegionRoute
  '/lol/feed/following': typeof LolFeedFollowingRoute
  '/lol/feed/for-you': typeof LolFeedForYouRoute
  '/lol/feed': typeof LolFeedIndexRoute
  '/lol/summoner': typeof LolSummonerIndexRoute
  '/lol/summoner/$riotID/charts': typeof LolSummonerRiotIDChartsRoute
  '/lol/summoner/$riotID/live': typeof LolSummonerRiotIDLiveRoute
  '/lol/summoner/$riotID/mastery': typeof LolSummonerRiotIDMasteryRoute
  '/lol/summoner/$riotID/matches': typeof LolSummonerRiotIDMatchesRoute
  '/lol/summoner/$riotID': typeof LolSummonerRiotIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/lol/feed': typeof LolFeedRouteRouteWithChildren
  '/lol/live': typeof LolLiveRoute
  '/r/$puuid': typeof RPuuidRoute
  '/user/accounts': typeof UserAccountsRoute
  '/user/settings': typeof UserSettingsRoute
  '/lol/summoner/$riotID': typeof LolSummonerRiotIDRouteRouteWithChildren
  '/lol/featured-games/$region': typeof LolFeaturedGamesRegionRoute
  '/lol/feed/following': typeof LolFeedFollowingRoute
  '/lol/feed/for-you': typeof LolFeedForYouRoute
  '/lol/feed/': typeof LolFeedIndexRoute
  '/lol/summoner/': typeof LolSummonerIndexRoute
  '/lol/summoner/$riotID/charts': typeof LolSummonerRiotIDChartsRoute
  '/lol/summoner/$riotID/live': typeof LolSummonerRiotIDLiveRoute
  '/lol/summoner/$riotID/mastery': typeof LolSummonerRiotIDMasteryRoute
  '/lol/summoner/$riotID/matches': typeof LolSummonerRiotIDMatchesRoute
  '/lol/summoner/$riotID/': typeof LolSummonerRiotIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/privacy'
    | '/terms'
    | '/lol/feed'
    | '/lol/live'
    | '/r/$puuid'
    | '/user/accounts'
    | '/user/settings'
    | '/lol/summoner/$riotID'
    | '/lol/featured-games/$region'
    | '/lol/feed/following'
    | '/lol/feed/for-you'
    | '/lol/feed/'
    | '/lol/summoner'
    | '/lol/summoner/$riotID/charts'
    | '/lol/summoner/$riotID/live'
    | '/lol/summoner/$riotID/mastery'
    | '/lol/summoner/$riotID/matches'
    | '/lol/summoner/$riotID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/privacy'
    | '/terms'
    | '/lol/live'
    | '/r/$puuid'
    | '/user/accounts'
    | '/user/settings'
    | '/lol/featured-games/$region'
    | '/lol/feed/following'
    | '/lol/feed/for-you'
    | '/lol/feed'
    | '/lol/summoner'
    | '/lol/summoner/$riotID/charts'
    | '/lol/summoner/$riotID/live'
    | '/lol/summoner/$riotID/mastery'
    | '/lol/summoner/$riotID/matches'
    | '/lol/summoner/$riotID'
  id:
    | '__root__'
    | '/'
    | '/user'
    | '/privacy'
    | '/terms'
    | '/lol/feed'
    | '/lol/live'
    | '/r/$puuid'
    | '/user/accounts'
    | '/user/settings'
    | '/lol/summoner/$riotID'
    | '/lol/featured-games/$region'
    | '/lol/feed/following'
    | '/lol/feed/for-you'
    | '/lol/feed/'
    | '/lol/summoner/'
    | '/lol/summoner/$riotID/charts'
    | '/lol/summoner/$riotID/live'
    | '/lol/summoner/$riotID/mastery'
    | '/lol/summoner/$riotID/matches'
    | '/lol/summoner/$riotID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRouteRoute: typeof UserRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LolFeedRouteRoute: typeof LolFeedRouteRouteWithChildren
  LolLiveRoute: typeof LolLiveRoute
  RPuuidRoute: typeof RPuuidRoute
  LolSummonerRiotIDRouteRoute: typeof LolSummonerRiotIDRouteRouteWithChildren
  LolFeaturedGamesRegionRoute: typeof LolFeaturedGamesRegionRoute
  LolSummonerIndexRoute: typeof LolSummonerIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/robots/txt': typeof RobotsTxtServerRoute
  '/sitemap-static/xml': typeof SitemapStaticXmlServerRoute
  '/sitemap/xml': typeof SitemapXmlServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/sitemap-summoners/$page/xml': typeof SitemapSummonersPageXmlServerRoute
}
export interface FileServerRoutesByTo {
  '/robots/txt': typeof RobotsTxtServerRoute
  '/sitemap-static/xml': typeof SitemapStaticXmlServerRoute
  '/sitemap/xml': typeof SitemapXmlServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/sitemap-summoners/$page/xml': typeof SitemapSummonersPageXmlServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/robots/txt': typeof RobotsTxtServerRoute
  '/sitemap-static/xml': typeof SitemapStaticXmlServerRoute
  '/sitemap/xml': typeof SitemapXmlServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/sitemap-summoners/$page/xml': typeof SitemapSummonersPageXmlServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/robots/txt'
    | '/sitemap-static/xml'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/sitemap-summoners/$page/xml'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/robots/txt'
    | '/sitemap-static/xml'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/sitemap-summoners/$page/xml'
  id:
    | '__root__'
    | '/robots/txt'
    | '/sitemap-static/xml'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/sitemap-summoners/$page/xml'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  RobotsTxtServerRoute: typeof RobotsTxtServerRoute
  SitemapStaticXmlServerRoute: typeof SitemapStaticXmlServerRoute
  SitemapXmlServerRoute: typeof SitemapXmlServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  SitemapSummonersPageXmlServerRoute: typeof SitemapSummonersPageXmlServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/accounts': {
      id: '/user/accounts'
      path: '/accounts'
      fullPath: '/user/accounts'
      preLoaderRoute: typeof UserAccountsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/r/$puuid': {
      id: '/r/$puuid'
      path: '/r/$puuid'
      fullPath: '/r/$puuid'
      preLoaderRoute: typeof RPuuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/live': {
      id: '/lol/live'
      path: '/lol/live'
      fullPath: '/lol/live'
      preLoaderRoute: typeof LolLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/feed': {
      id: '/lol/feed'
      path: '/lol/feed'
      fullPath: '/lol/feed'
      preLoaderRoute: typeof LolFeedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/summoner/': {
      id: '/lol/summoner/'
      path: '/lol/summoner'
      fullPath: '/lol/summoner'
      preLoaderRoute: typeof LolSummonerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/feed/': {
      id: '/lol/feed/'
      path: '/'
      fullPath: '/lol/feed/'
      preLoaderRoute: typeof LolFeedIndexRouteImport
      parentRoute: typeof LolFeedRouteRoute
    }
    '/lol/feed/for-you': {
      id: '/lol/feed/for-you'
      path: '/for-you'
      fullPath: '/lol/feed/for-you'
      preLoaderRoute: typeof LolFeedForYouRouteImport
      parentRoute: typeof LolFeedRouteRoute
    }
    '/lol/feed/following': {
      id: '/lol/feed/following'
      path: '/following'
      fullPath: '/lol/feed/following'
      preLoaderRoute: typeof LolFeedFollowingRouteImport
      parentRoute: typeof LolFeedRouteRoute
    }
    '/lol/featured-games/$region': {
      id: '/lol/featured-games/$region'
      path: '/lol/featured-games/$region'
      fullPath: '/lol/featured-games/$region'
      preLoaderRoute: typeof LolFeaturedGamesRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/summoner/$riotID': {
      id: '/lol/summoner/$riotID'
      path: '/lol/summoner/$riotID'
      fullPath: '/lol/summoner/$riotID'
      preLoaderRoute: typeof LolSummonerRiotIDRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/summoner/$riotID/': {
      id: '/lol/summoner/$riotID/'
      path: '/'
      fullPath: '/lol/summoner/$riotID/'
      preLoaderRoute: typeof LolSummonerRiotIDIndexRouteImport
      parentRoute: typeof LolSummonerRiotIDRouteRoute
    }
    '/lol/summoner/$riotID/matches': {
      id: '/lol/summoner/$riotID/matches'
      path: '/matches'
      fullPath: '/lol/summoner/$riotID/matches'
      preLoaderRoute: typeof LolSummonerRiotIDMatchesRouteImport
      parentRoute: typeof LolSummonerRiotIDRouteRoute
    }
    '/lol/summoner/$riotID/mastery': {
      id: '/lol/summoner/$riotID/mastery'
      path: '/mastery'
      fullPath: '/lol/summoner/$riotID/mastery'
      preLoaderRoute: typeof LolSummonerRiotIDMasteryRouteImport
      parentRoute: typeof LolSummonerRiotIDRouteRoute
    }
    '/lol/summoner/$riotID/live': {
      id: '/lol/summoner/$riotID/live'
      path: '/live'
      fullPath: '/lol/summoner/$riotID/live'
      preLoaderRoute: typeof LolSummonerRiotIDLiveRouteImport
      parentRoute: typeof LolSummonerRiotIDRouteRoute
    }
    '/lol/summoner/$riotID/charts': {
      id: '/lol/summoner/$riotID/charts'
      path: '/charts'
      fullPath: '/lol/summoner/$riotID/charts'
      preLoaderRoute: typeof LolSummonerRiotIDChartsRouteImport
      parentRoute: typeof LolSummonerRiotIDRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/sitemap-static/xml': {
      id: '/sitemap-static/xml'
      path: '/sitemap-static/xml'
      fullPath: '/sitemap-static/xml'
      preLoaderRoute: typeof SitemapStaticXmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/sitemap-summoners/$page/xml': {
      id: '/sitemap-summoners/$page/xml'
      path: '/sitemap-summoners/$page/xml'
      fullPath: '/sitemap-summoners/$page/xml'
      preLoaderRoute: typeof SitemapSummonersPageXmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface UserRouteRouteChildren {
  UserAccountsRoute: typeof UserAccountsRoute
  UserSettingsRoute: typeof UserSettingsRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAccountsRoute: UserAccountsRoute,
  UserSettingsRoute: UserSettingsRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface LolFeedRouteRouteChildren {
  LolFeedFollowingRoute: typeof LolFeedFollowingRoute
  LolFeedForYouRoute: typeof LolFeedForYouRoute
  LolFeedIndexRoute: typeof LolFeedIndexRoute
}

const LolFeedRouteRouteChildren: LolFeedRouteRouteChildren = {
  LolFeedFollowingRoute: LolFeedFollowingRoute,
  LolFeedForYouRoute: LolFeedForYouRoute,
  LolFeedIndexRoute: LolFeedIndexRoute,
}

const LolFeedRouteRouteWithChildren = LolFeedRouteRoute._addFileChildren(
  LolFeedRouteRouteChildren,
)

interface LolSummonerRiotIDRouteRouteChildren {
  LolSummonerRiotIDChartsRoute: typeof LolSummonerRiotIDChartsRoute
  LolSummonerRiotIDLiveRoute: typeof LolSummonerRiotIDLiveRoute
  LolSummonerRiotIDMasteryRoute: typeof LolSummonerRiotIDMasteryRoute
  LolSummonerRiotIDMatchesRoute: typeof LolSummonerRiotIDMatchesRoute
  LolSummonerRiotIDIndexRoute: typeof LolSummonerRiotIDIndexRoute
}

const LolSummonerRiotIDRouteRouteChildren: LolSummonerRiotIDRouteRouteChildren =
  {
    LolSummonerRiotIDChartsRoute: LolSummonerRiotIDChartsRoute,
    LolSummonerRiotIDLiveRoute: LolSummonerRiotIDLiveRoute,
    LolSummonerRiotIDMasteryRoute: LolSummonerRiotIDMasteryRoute,
    LolSummonerRiotIDMatchesRoute: LolSummonerRiotIDMatchesRoute,
    LolSummonerRiotIDIndexRoute: LolSummonerRiotIDIndexRoute,
  }

const LolSummonerRiotIDRouteRouteWithChildren =
  LolSummonerRiotIDRouteRoute._addFileChildren(
    LolSummonerRiotIDRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRouteRoute: UserRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LolFeedRouteRoute: LolFeedRouteRouteWithChildren,
  LolLiveRoute: LolLiveRoute,
  RPuuidRoute: RPuuidRoute,
  LolSummonerRiotIDRouteRoute: LolSummonerRiotIDRouteRouteWithChildren,
  LolFeaturedGamesRegionRoute: LolFeaturedGamesRegionRoute,
  LolSummonerIndexRoute: LolSummonerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  RobotsTxtServerRoute: RobotsTxtServerRoute,
  SitemapStaticXmlServerRoute: SitemapStaticXmlServerRoute,
  SitemapXmlServerRoute: SitemapXmlServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  SitemapSummonersPageXmlServerRoute: SitemapSummonersPageXmlServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
